# Generated by Django 2.0.7 on 2018-08-03 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yomarket', '0002_shop_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='offers_from_category', to='common.Category'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='shops_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
